### ISSUE TITLE
Not compatible with iOS 11

### ISSUE THREAD

**Issue by chenyunguiMilook** [marmelroy/Zip#101]
<img width="314" alt="2017-09-20 9 53 31" src="https://user-images.githubusercontent.com/11513291/30623347-93ef7e7e-9de9-11e7-8004-a8eff579aa6d.png">

**Comment by marmelroy** [comment]
Solved by release 1.0.0

**Comment by gkaimakas** [comment]
@marmelroy I tried using zip (1.0.0) with Xcode 9 (9.0) and I got the same errors.
