### ISSUE TITLE
Request: Extract only specific files form archive

### ISSUE THREAD

**Issue by JurekRaben** [marmelroy/Zip#105]
Hi,

I have a scenario where I want to extract 1000 of zip archives, each having the same file structure and only interested in one specific file in each archive.

Is it possible that you would add such a feature, so it uses less cpu and memory?

Also it seems to me that this lib is quite a memory hog?

Thanks

**Comment by marmelroy** [comment]
Hi @JurekRaben, this is a very specific need and not one that is currently served by Zip. Sorry about that. If you have specific observation of high memory usage, PRs are welcome.
