### ISSUE TITLE
Report progress on the extracted file

### ISSUE THREAD

**Issue by pgodino** [marmelroy/Zip#108]
Currently the progress reports only the files extracted. I propose to add also a progress that is relative to the currently extracted file.

**Comment by marmelroy** [comment]
Thanks @pgodino - resolved by your PR (released in 1.1.0)

**Comment by namannik** [comment]
I've downloaded release 1.1.0, and it doesn't include the change made in pull request (#109).  Specifically, I'm looking for the new `fileProgress` parameter.  Am I missing something here?
