### ISSUE TITLE
Provide binary builds for Carthage

### ISSUE THREAD

**Issue by mikeger** [marmelroy/Zip#11]
Hey

I would like to point out that it would be nice to provide the binary builds of Zip framework along with the releases. This way the framework users would not have to compile the framework each time they do the `carthage bootstrap`.
Reference: [Carthage manual](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file)

With kind regards, Mike.

**Comment by marmelroy** [comment]
Carthage support was dropped.
