### ISSUE TITLE
Error while unzip .zip archive

### ISSUE THREAD

**Issue by JimmyYezeguelian** [marmelroy/Zip#14]
Hi, i'm triyng to unzip a .zip archive.
I've installed Zip by cocoapods and used like this :

            do {
                try Zip.unzipFile(NSURL(fileURLWithPath: docPath), destination: NSURL(fileURLWithPath: unzipedDocPath), overwrite: true, password: nil, progress: { (progress) -> () in
                    print(progress)
                }) // Unzip
                
            } catch let error as NSError {
                print("Error: \(error)")
            }

But I get this error ...
Thank by the advence

**Comment by marmelroy** [comment]
Thanks @JimmyYezeguelian. There's nothing obviously wrong that should produce the error. Any chance you can upload the zip file and paste the docPath and unzipedDocPath?

**Comment by JimmyYezeguelian** [comment]
This is my filePath to unzip:
> /var/mobile/Containers/Data/Application/AE2C328C-7DEC-4697-B3FB-6A03A662D57A/Downloads/politiquedecom.zip
And my folder to unzip:
> /var/mobile/Containers/Data/Application/AE2C328C-7DEC-4697-B3FB-6A03A662D57A/Documents/politiquedecom

Then, i just don't know if the NSURL needed is like NSURL(string: ) or NSURL(fileURLWithPath: )

**Comment by JimmyYezeguelian** [comment]
Finale Works ! 
That's was just my folder not exists ... Sorry about that !

Thanks

**Comment by marmelroy** [comment]
Hehe. No worries. 😄
