### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by jwkwon** [marmelroy/Zip#147]
Hi,

I just cloned the repo and tried lint on it as follows

$ pod lib lint

 -> Zip (1.1.0)
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  /Users/jason/Downloads/Zip/Zip/Zip.swift:10:8: error: no such module 'Minizip'

[!] Zip did not pass validation, due to 2 errors.
You can use the `--no-clean` option to inspect any issue.

How did you manage to get this on the pod? It looks like lint is failing to build it. Is there any magic configuration for the build to succeed? Any help will be appreciated. Thanks!

**Comment by MarcSteven** [comment]
@jwkwon  perhaps the library is not maintained by the author again.

**Comment by marmelroy** [comment]
This should be fixed now. Closing as outdated.
