### ISSUE TITLE
Invalid Archive with Password

### ISSUE THREAD

**Issue by ahsanmuzafar** [marmelroy/Zip#15]
Archive is Invalid When Created with password. 
when password is  nil it works perfect

**Comment by marmelroy** [comment]
Hi @ahsanmuzafar, 

So... it's not actually invalid. What happens is, Zip uses AES-256 encryption for password protection and there are many desktop zip utilities that don't currently support AES-256. 

If you're on OSX, I recommend using http://www.kekaosx.com/en/.

**Comment by ahsanmuzafar** [comment]
it is not working on windows as well. i tried to open archive with different utilities . same error

**Comment by marmelroy** [comment]
Could you please upload your zip file here?

**Comment by ahsanmuzafar** [comment]
[Nicki Minaj - Super Bass.zip](https://github.com/marmelroy/Zip/files/270304/Nicki.Minaj.-.Super.Bass.zip)
password 123

**Comment by ahsanmuzafar** [comment]
Have you found the issue ?

**Comment by orhanmaden** [comment]
It's true that zip doesn't work with the default archiver. I tested it also with the unarchiver and that also didn't work. With keka it did work.
