### ISSUE TITLE
Official release for Xcode 10.1

### ISSUE THREAD

**Issue by mrinalsymc** [marmelroy/Zip#158]
Hi,

Currently in my project we are using the tip of the master cause 1.1.0 doesnt build with xcode 10.1. Are there any estimates when there is going to an official release for xcode 10.1

any thoughts , @marmelroy ?
Thanks.

**Comment by Aranoledur** [comment]
Any update? If there is no one to support Zip right now, maybe you can give release rights to someone who have time?

**Comment by MarcSteven** [comment]
Perhaps the author didn't maintain the project again ,there are lots of issues ,by the way you can choose some other tool ,or you write the framework by yourself ,there is less framework about it ....I don't know why it's not fashion , @marmelroy perhaps doesn't have enough time to do it .

**Comment by marmelroy** [comment]
This is outdated now. I am always looking for additional contributors to help manage Zip. Please reach out on twitter if you're interested.
