### ISSUE TITLE
Please submit the Zip.podspec you have in this repo to CocoaPod trunk repository!

### ISSUE THREAD

**Issue by marcosiino** [marmelroy/Zip#161]
I have noticed you have approved a PR with a commit which adds s.swift_version in Zip.podpsec. This is a very nice things that solves a problem we (and many other users) had when using your pod in a project which uses swift < 4.0.

Unfortunately you haven't pushed this updated Zip.podspec to CocoaPod Trunk, so we cannot benefit this (infact if i use your library in my Podfile, the old version of the podspec without the s.swift_version is used, which causes build errors in projects which uses swift < 4.x).

Please, i ask you to kindly push the updated Zip.podspec to CocoaPod Trunk using "pod trunk push Zip.podspec" command.

I hope you can do this asap, we are using a dependency which uses your pod, and without this we are blocked.

Thank you ;)

**Comment by earthbound19** [comment]
+1 this

**Comment by marmelroy** [comment]
This is already pushed - sorry for the lateness
