### ISSUE TITLE
Zip has not set SWIFT_VERSION 

### ISSUE THREAD

**Issue by MartinWong-H** [marmelroy/Zip#164]
`Zip` does not specify a Swift version and none of the targets (`RoWrite`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by haoyuant** [comment]
same issue here

**Comment by PyariDevi** [comment]
i am also facing the similar issue

[!] Unable to determine Swift version for the following pods:

- `Zip` does not specify a Swift version and none of the targets (`App`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by Xiahaiquan** [comment]
In "buildSettings", you can click "buildSettings" and add "SWIFT_VERSION" key ,then set the value is "3.0" , after all, in cocopods  "pod update --verbose --no-repo-update"


![屏幕快照 2019-07-11 15 56 37](https://user-images.githubusercontent.com/16540292/61032718-8d54bf80-a3f4-11e9-8a1f-61bc8e97b667.png)
![屏幕快照 2019-07-11 15 56 56](https://user-images.githubusercontent.com/16540292/61032722-8fb71980-a3f4-11e9-8907-a08fc09e4141.png)

**Comment by marmelroy** [comment]
This should be fixed now
