### ISSUE TITLE
New Release / TAG

### ISSUE THREAD

**Issue by kapizoli77** [marmelroy/Zip#180]
Can you please create a new TAG? The 'minizip' fix in master branch isn't released under a new tag. Thanks!

**Comment by hhunaid** [comment]
There hasn't been a new Tag in 2 years I guess. I can't list this library as a dependency in my pod because of that.

**Comment by mateuszjablonski** [comment]
@hhunaid You can try:
`pod 'Zip', :git => 'https://github.com/marmelroy/Zip', :commit => '45c25175a606ec78adf3e75ea50df54151b86515'`

Of course this is just a walkaround, so @marmelroy, `pod trunk push Zip.podspec `, if you please.

**Comment by bjo0** [comment]
@AvdLee just published 2.0.0. I think this can be marked as completed.

**Comment by marmelroy** [comment]
This is now outdated - closing.
