### ISSUE TITLE
Xcode 11.1, swift 5.1

### ISSUE THREAD

**Issue by nttri** [marmelroy/Zip#181]
Did this lib worked on project using xcode 11.1 + swift 5.1 ? I saw the commit on master about this but the release note didn't. Thanks guy.

**Comment by CraigSiemens** [comment]
Yes, I'm currently using it with Swift 5.1.

**Comment by noppefoxwolf** [comment]
Yes, But you should configure master branch.
1.1.0 not support xcode11~.

**Comment by marmelroy** [comment]
This is now outdated - closing.
