### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by mohamede1945** [marmelroy/Zip#187]
Can you release a new version please? Just create a tag with that's in master. Currently to use this repo with SwiftPM we have to point to master branch as tag 1.11 doesn't have SwiftPM support.

**Comment by elmo5676** [comment]
Any progress on this? No version works and I would love to use this.

**Comment by jncn** [comment]
Same here: would love to use Zip with SwiftPM, but the last version doesn't have a manifest.

**Comment by klmitchell2** [comment]
Would also enjoy this to be updated. Happy to help if thats what's needed.

**Comment by bjo0** [comment]
Please tag, for example: `2.0.0-alpha.1`

**Comment by bjo0** [comment]
@AvdLee just published 2.0.0. I have confirmed that SwiftPM can resolve it. I think this can be marked as completed.

**Comment by marmelroy** [comment]
This is now outdated. I am always looking for new contributors to Zip. Please reach out via Twitter DMs if interested.
