### ISSUE TITLE
Missing required module 'minizip'

### ISSUE THREAD

**Issue by blg-nb** [marmelroy/Zip#19]
Hello,

i integrated your Zip Framework in my swift project with cocoapods

In my podfile:
`pod 'Zip', '~> 0.4'` Download the version 0.4.1

I have an error on the import Zip line in my swift file: Missing rqquired module 'minizip'
This Error is only on simulator. On device it works.

**Comment by CodeEagle** [comment]
carthage same!

**Comment by blg-nb** [comment]
I dont use carthage ...

**Comment by gsimmons** [comment]
This is still an issue. If you don't check the code into your repo, then other people won't be able to build. The built framework should be enough by itself. You shouldn't also need the code files to be present in order for your project to be build.

**Comment by lvcloudgit** [comment]
This is embarrassing... It works fine on simulator but got this error on real devices.
So I add the minizip folder to Import path, then it can run on real devices but can't run on simulator... what's the problem anyway?

**Comment by marmelroy** [comment]
for reference, this was resolved by release 0.6.0 that checked in the minizip dependency instead of relying on git submodules.

**Comment by lvcloudgit** [comment]
@marmelroy  Thanks for reply, I'm a new coder, and I can't use Cocoapods, just Carthage, what should I do to fix this? Please guide me more details, thank you!

**Comment by marmelroy** [comment]
@lvcloudgit, I suggested five steps on your other issue - https://github.com/marmelroy/Zip/issues/50
