### ISSUE TITLE
Need a tagged version with Swift 5.1 support

### ISSUE THREAD

**Issue by bjo0** [marmelroy/Zip#191]

**Comment by bjo0** [comment]
Given that the Swift version was bumped on master since the 1.1.0 release, I propose: `2.0.0-alpha.1`

**Comment by bjo0** [comment]
Dupe of #187 I guess

**Comment by bjo0** [comment]
Also #180

**Comment by Leopardstoryboard** [comment]
what is that ? i don't know

**Comment by bjo0** [comment]
@AvdLee just published 2.0.0. I have confirmed that SwiftPM can resolve it. I think this can be marked as completed.
