### ISSUE TITLE
Version 2.0.0 using Swift Package Manager is missing minizip

### ISSUE THREAD

**Issue by MarcoFilosi** [marmelroy/Zip#193]
In latest version 2.0.0 using Swift Package Manager on XCode 11.4.1 code cannot compile because of "missing required module 'Minizip'".
Please fix it as soon as possible, or, in alternative, make version 2.0.0 available on CocoaPods too.
Thanks

This issue seems to be similar to issue #134 

![Screenshot 2020-05-04 at 22 34 35](https://user-images.githubusercontent.com/1218291/81104507-e7d68380-8f12-11ea-9cc3-00e901aeef50.png)

**Comment by baluhman** [comment]
The same problem too using SPM in Xcode 11.5!
<img width="993" alt="Снимок экрана 2020-06-26 в 10 30 18" src="https://user-images.githubusercontent.com/30830934/85832057-0e3cd080-b798-11ea-9e06-2411e8826de3.png">

**Comment by marmelroy** [comment]
This should be fixed now. Sorry for the lateness.

**Comment by MarcoFilosi** [comment]
No it has not been fixed at all.
Tried on XCode 12.0.1 using Zip v. 2.1.1. The error persists:

<img width="895" alt="Screenshot 2020-10-01 at 08 32 49" src="https://user-images.githubusercontent.com/1218291/94775909-00af6c00-03c1-11eb-8414-08ff2b47c8ef.png">

**Comment by VittoriDavide** [comment]
I have this error too when using on Share Target, Xcode 12.3 (12C33)

**Comment by baluhman** [comment]
i think so this is not library issue. It`s problem in SPM
I solved this when fix wrong linked modules in projects

**Comment by C4Framework** [comment]
@baluhman how did you fix this?

**Comment by baluhman** [comment]
@C4Framework how I said before I was fixed wrong linked modules in my project. But it is actual for my project because it contains many modules(frameworks)
