### ISSUE TITLE
Cannot work with pods

### ISSUE THREAD

**Issue by mayqiyue** [marmelroy/Zip#201]
xcode 11.6

this is my podfile:

```
target 'ZipForRecam' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  pod 'Zip', :git=>'https://github.com/marmelroy/Zip.git'
  pod 'Minizip'

  # Pods for ZipForRecam

end

```

but it doesn't work: 
No such module 'Minizip'

**Comment by marmelroy** [comment]
Thanks for letting me know @mayqiyue. Recent changes broke cocoapods integration. This is now fixed with release 2.2.1

You can remove  pod 'Minizip' from your pod file as it's not necessary.
