### ISSUE TITLE
Error when use version 2.1.2

### ISSUE THREAD

**Issue by paulocoutinhox** [marmelroy/Zip#236]
Hi,

I get error when use version 2.1.2:

```
Pods/Zip/Zip/minizip/zip.c:22:10: error build: 'zip.h' file not found
```

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/395096/193111015-504f4580-2974-4f8e-84d3-8d6330a685b6.png">

**Comment by fermoya** [comment]
I have the same issue, @paulocoutinhox did you find the problem?

**Comment by paulocoutinhox** [comment]
Hi, no, i never use it more.
