### ISSUE TITLE
Error - Missing required module 'minizip'

### ISSUE THREAD

**Issue by gsimmons** [marmelroy/Zip#24]
This occurs when the Zip code files are not present. We use carthage to check out and build dependencies, but we don't commit the code / project files into our repo, just the built frameworks. When another dev checks out the project, they get this error. The built framework should be independent of the project / code files.

**Comment by Zyphrax** [comment]
I am having the same issue trying to migrate to swift 3.0 with CocoaPods

**Comment by timrichardsn** [comment]
Same issue here

**Comment by Zyphrax** [comment]
@timrichardsn I found out that you have to specify the submodules option:
`pod 'Zip', git: 'https://github.com/marmelroy/Zip', branch: 'swift3.0', submodules: true`

CocoaPods ignores options related to the source of the original podspec.

**Comment by timrichardsn** [comment]
@Zyphrax Awesome, thanks for that

**Comment by michelefranco** [comment]
What about Carthage? Did anyone find a solution?

**Comment by marmelroy** [comment]
Hi everyone. Readme updated to include submodules: true. 

I couldn't find a Carthage solution and Carthage was removed from the README.

**Comment by jakerockland** [comment]
Hey @marmelroy, was a bit curious about this being a closed issue as I still seem to be having this issue w/ Swift 3 and Carthage. I'm able to have things work if I re-checkout the files, but shouldn't the built frameworks be independent of the checked out project files?

**Comment by icaksama** [comment]
Try this when build with carthage :
carthage update --use-submodules

After that, Add your Zip.framework to project and add Zip.framework in General -> Embedded Binaries

**Comment by vCrespoP** [comment]
Any chance this gets reopened? Still happening today with Carthage. Using submodules seems to work but I'm not sure this is Carthage's philosophy where you don't have dependencies among frameworks?

**Comment by macness-pavelh** [comment]
Having similar issues related to minizip module when using Zip in my own library deployed trough CocoaPods. 

Proposal: in Zip project create minizip static module target (as three targets for each platform, possibly) and link it statically. After this any external projects linking zip would not be aware of minizip at all. This might (or not) solve similar problems.

The evil seems to be in SWIFT_INSCLUDE_PATH pointing to minizip module. This path is then retained even in modules using Zip, potentially resulting to module redefinition (different but related issue to what's being discussed here).

**Comment by jhoughjr** [comment]
I"m having this issue as well. Spent many hours on it. I've resolved it for me but not other devs on our team.

**Comment by ltblueberry0** [comment]
having the same issue with carthage

**Comment by pjcau** [comment]
I'm the same issue. Have you news?

**Comment by Zyphrax** [comment]
@chriswill0w @pjcau How do you include Zip in your Cartfile?
The following works fine in our iOS app:

```
github "marmelroy/Zip"
```

Make sure you use the latest version of Carthage:
```
$ carthage version
0.32.0
```

If all fails, a good old Carthage reset sometimes works wonders:
1. remove the Carthage folder
2. remove the Cartfile.lock
3. carthage update
