### ISSUE TITLE
Does not work for command line tool

### ISSUE THREAD

**Issue by PjotrC** [marmelroy/Zip#26]
I am getting following error, when using on a Command Line Tool project:

dyld: Library not loaded: @rpath/Zip.framework/Versions/A/Zip
  Referenced from: /Users/macOS/Library/Developer/Xcode/DerivedData/Test_Zip-cjrtsqmggijipgaqvctjpbltwtxs/Build/Products/Debug/Test_Zip
  Reason: image not found
(lldb) 

In a Cocoa Application project it works.
PS: I used Cocoapods to create the workspace.

EDIT:
It seems, that generally this is not possible: all libraries I tried gave this error when using in a Command Line Tool project. Why is this?

**Comment by marmelroy** [comment]
Sorry for the delay.

Doesn't seem like this is a Zip issue. Closing.
