### ISSUE TITLE
Zipping a folder

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [marmelroy/Zip#3]
I tested this this library with zipping a bunch of files *inside* a folder and it works great. However zipping that said folder itself results in a file of a format called CPGZ when it is unzipped.

![screen shot 2016-01-21 at 9 06 42 am](https://cloud.githubusercontent.com/assets/2551877/12487989/560ffb10-c01e-11e5-9f53-cc1a6a745a4b.png)

Is zipping a folder not supported or am I doing something wrong? Here's the snippet of code.

```swift
do {
    let folderPath = NSBundle.mainBundle().bundleURL.URLByAppendingPathComponent("My Images")
    try Zip.zipFiles([folderPath], zipFilePath: zipPath, password: nil, progress: { progress in
        print(progress)
    })
} catch {
    print("Zipping failed :(")
}
```

I've uploaded a demo project to Dropbox [here](https://www.dropbox.com/s/f2370yzh7gfvjyv/ZipSwift.zip?dl=0).

**Comment by marmelroy** [comment]
zipFiles is currently expecting NSURLs of filePaths and not a folderPath. You can grab the contents of the folder path and pass them to zipFiles. 

That said, being able to zip a folder path would be useful. I'll add this to a future version.

**Comment by marmelroy** [comment]
Hi @Isuru-Nanayakkara, this is now solved with https://github.com/marmelroy/Zip/commit/075ee6cbdbdc5833809511d3c90d3690da7cfcfe

I want to add some folder-specific tests before bundling this feature in the next release but you can try it in the meantime. 

Thanks again for the question. Closing this issue.

**Comment by marmelroy** [comment]
Released.
