### ISSUE TITLE
Carthage Issue

### ISSUE THREAD

**Issue by Sudhi55** [marmelroy/Zip#45]
Getting this error on Carthage update on Xcode 8 - A shell task (/usr/bin/env git checkout --quiet c69afd6a7712d31287921386ddb94ca206cb727e) failed with exit code 128:
fatal: reference is not a tree: c69afd6a7712d31287921386ddb94ca206cb727e

**Comment by PiotrStepien** [comment]
I've got the same issue. Any solution?

**Comment by marmelroy** [comment]
Fixed. Sorry @Sudhi55 and @PiotrStepien.
