### ISSUE TITLE
Unzip from NSData

### ISSUE THREAD

**Issue by athei** [marmelroy/Zip#46]
Would it be possible to add a feature to uncompress an archive stored as NSData instead of a file on disk? This is useful when rather small files are downloaded and no temporary download location is needed.

**Comment by marmelroy** [comment]
Hi @athei! That's an interesting idea. With the current minizip integration, a file path is needed to unzip. 

We could theoretically write a helper that would create a temporary file path to unzip NSData but I'm not sure if this is a common enough use case. Closing for now.

**Comment by anonym24** [comment]
In Java/Kotlin you can all that stuff in memory, not temporary file is needed

                val zipStream = ZipInputStream(inputStream) // inputStream - data downloaded from internet (zip file)
                zipStream.nextEntry // unzip first .json file insize zip archieve
                val reader = InputStreamReader(zipStream, Charsets.UTF_8)
                val array = Gson().fromJson(reader, JsonArray::class.java)
                reader.close()
                zipStream.close()
                inputStream.close()

**Comment by anonym24** [comment]
I've created a next question on SO

https://stackoverflow.com/questions/55089278/how-can-i-get-zip-from-data-object-and-unzip-first-entry-file-inside-it

**Comment by anonym24** [comment]
Something tells me it's that easy. I can't find any examples
