### ISSUE TITLE
Error in Carthage

### ISSUE THREAD

**Issue by GrayLand119** [marmelroy/Zip#47]
```
*** Fetching Zip
*** Checking out Zip at "0.6.0"
*** xcodebuild output can be found in /var/folders/gq/2y8v_smd6rxf2gsr7hbdx9w80000gn/T/carthage-xcodebuild.W6LYN2.log
*** Building scheme "Zip" in Zip.xcodeproj

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

```

**Comment by marmelroy** [comment]
Hi @GrayLand119, the new version of Zip is the Swift 3.0 release and I believe that might be part of the issue you are facing. Are you using Xcode 8?

**Comment by GrayLand119** [comment]
@marmelroy  THX~  I have installed xcode8 but i selected the xcode7.3.1 default. And i switch to xcode8 with command "xcode-select -s [XCODE8_PATH]" then retry , update success!

**Comment by marmelroy** [comment]
Happy to hear.
