### ISSUE TITLE
Can't unzip on real phone

### ISSUE THREAD

**Issue by lvcloudgit** [marmelroy/Zip#48]
It works well on simulator, but can't work on real device.
I tried to unzip a file to Documents directory, and got error ("Zip.ZipError" Error 0.).
Also be told: doesn't have authority to write in Documents folder. But I can do create, move or delete, just can't unzip.
Also can't google out any information about this situation, could anyone help me out of this?
Thanks a lot !

**Comment by marmelroy** [comment]
Duplicate of https://github.com/marmelroy/Zip/issues/50
