### ISSUE TITLE
Unzipping zip archives that were created on Windows with 7Zip

### ISSUE THREAD

**Issue by TobiasWGDE** [marmelroy/Zip#5]
Dear Mr. Roy Marmelstein

This is for sure not a bug. But I have not found a solution for the following problem. Maybe you can give me a quick advice.

If I create a zip archive with the OS X default compression feature that's integrated in Finder and extract this archive again with Zip.unzip then unzipping works.

If I create an archive on Windows with 7Zip then Zip.unzip throws an exception 'Error.UnzipFail' in file 'zip.swift' at line 92 because 'unzOpenCurrentFile' returned with -103 (UNZ_BADZIPFILE).

I have tryed all zip compression algorithms that are offered by 7Zip: Deflate, Deflate64, BZip2, LZMA and PPMd.

Can you tell me the algorithm to use for compression, to successfully extract archives with your library on iOS?

Yours sincerely
Tobias Miller

**Comment by marmelroy** [comment]
Hey @TobiasWGDE, that's an interesting issue. Zip is built on top of minizip (https://github.com/nmoinvaz/minizip). Maybe it's missing something to deal with Windows-produced zip files. I'm afraid I won't be able to look into this until Tuesday though...

**Comment by TobiasWGDE** [comment]
i've investigated the problem further and could track this behavior down to a case where it seems that I can reproduce the bug, but not reliably. Whether the bug occurs or not, seemingly depends on randomly moving some files or folders out of or into the directory structure that gets zipped.

One thing I haven't mention, is that the files were originally created on OS X 10.11.2 and then transferred with dropbox to a Windows 10 system.

Maybe this is some kind of random CRC-Bug caused by 7Zip, that minizip can't handle. Or there are file system level encoding issues between Mac FS, dropbox cloud storage and NTFS.

Tomorrow I will try to attache some example archives.

**Comment by TobiasWGDE** [comment]
Here are the archives. The archives were created with 7Zip. Algorithm: 'Deflate', All other compression settings were left in their defaults.

original_content.zip contains the files and folders, which should be zipped:
It has a top level folder, that contains text files, images and a 'gallery' folder. The 'gallery' folder contains again text files, images and a 'thumbs' folder. The 'thumbs' folder contains images only.


These are working:
without_thumbs_folder.zip: Everything but the 'thumbs' folder
thumbs_folder_only.zip: Only the 'thumbs' folder

These don't:
original_content.zip
original_content_copied_some_files_rm.zip: Copied to an other location, then I removed some files in each folder.

[original_content.zip](https://github.com/marmelroy/Zip/files/152300/original_content.zip)
[original_content_copied_than_some_file_rm.zip](https://github.com/marmelroy/Zip/files/152299/original_content_copied_than_some_file_rm.zip)
[thumbs_folder_moved_one_level_up.zip](https://github.com/marmelroy/Zip/files/152302/thumbs_folder_moved_one_level_up.zip)
[thumbs_folder_only.zip](https://github.com/marmelroy/Zip/files/152301/thumbs_folder_only.zip)
[thumbs_folder_removed.zip](https://github.com/marmelroy/Zip/files/152303/thumbs_folder_removed.zip)




thumbs_folder_moved_one_level_up.zip: Same as original_content.zip but 'thumbs' folder moved one level up.

**Comment by marmelroy** [comment]
Hi @TobiasWGDE, thanks for adding the files. 

I ran some tests and found the issue. In all the files that don't work, the top-level-folder contains a special character - for example, in original_content.zip, the top-level folder is
``` test_flie·text ```

It looks like 7zip doesn't encode the character · correctly and Zip is unable to cast it to String/NSString. That is what is causing the failure.

Other compression tools (tested with Apple's Archive utility) can encode the character · without an issue.
