### ISSUE TITLE
Package.swift has mixed language and won't compile on swift build

### ISSUE THREAD

**Issue by elk941** [marmelroy/Zip#52]
When running swift build a project that includes Zip, I get the following terminal output:

Cloning https://github.com/marmelroy/Zip.git
HEAD is now at 852a776 Delete git submodule
Resolved version: 0.6.0
error: the module at <MyProjectPath>/Packages/Zip-0.6.0/Zip contains mixed language source files
fix: use only a single language within a module

**Comment by marmelroy** [comment]
Thanks @elk941 ! 

Zip is built on top of minizip, a C framework, and thus contains some C source files.

SPM unfortunately can't handle the C files yet and is therefore unsupported. I would suggest to use Cocoapods or Carthage to compile the dynamic framework and integrate it in your project.
