### ISSUE TITLE
Remove Package.swift ?

### ISSUE THREAD

**Issue by mostafaberg** [marmelroy/Zip#53]
I saw that there is a Package.swift file, however the library uses mixed languages (c, etc..) for Zip support, making it not available for SPM (yet), maybe it's better to remove that file to avoid developers assuming that it'll work ?

**Comment by marmelroy** [comment]
Not a bad idea.

**Comment by marmelroy** [comment]
https://github.com/marmelroy/Zip/commit/6f3b6b442b9c8711068178c3c6c9da4bf75f52b4
