### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by falipate** [marmelroy/Zip#54]
I updated to Xcode 8, swift 3, also updated Zip to 0.6.0 and now I have all these errors:
![screen shot 2016-10-05 at 4 28 05 pm](https://cloud.githubusercontent.com/assets/12621961/19102039/c2127f98-8b18-11e6-820f-daf6cfd96462.png)

**Comment by marmelroy** [comment]
The fact you see an "undeclared type URL" error means your app is still not using Swift 3.0.

Go into your build settings and make sure "Use legacy swift version" is set to NO.

**Comment by falipate** [comment]
I changed the "Use legacy swift version" to NO, cleaned the project and the same errors still appeared

**Comment by marmelroy** [comment]
Eek... is it possible for you to share some of your code?

**Comment by falipate** [comment]
Adding in the library in manually seemed to fix it

**Comment by mostafaberg** [comment]
@falipate What's your cocoapods version 
?
