### ISSUE TITLE
Missing required module "minizip"

### ISSUE THREAD

**Issue by PiotrStepien** [marmelroy/Zip#58]
I installed Zip using carthfile and when I try to build this framework I get information about missing module "minizip". What do I need to do, to use this framework?

**Comment by jhanzo** [comment]
+ 1 reproducing the issue

**Comment by mostafaberg** [comment]
Does it work when you add this to your cartfile ?

`github "dexman/Minizip"`

**Comment by jhanzo** [comment]
(Using swift 2.3, xcode 8) I reproduce the issue with following pod lines : 
- pod 'Zip', :git => 'https://github.com/marmelroy/Zip.git', :branch => 'swift2.3'
Or
- pod 'Zip', '~> 0.4'

**Comment by mostafaberg** [comment]
@jhanzo Your issue is not Carthage related, I would recommend opening another issue for that.
From what I know is that `Swift 2.3` is not officially supported, I would recommend going directly to `Swift 3.0` since that is tested and works out of the box

**Comment by jhanzo** [comment]
👍  for new issue. Swift 2.3 is a required need since all our pods are not on swift 3 yet :(

**Comment by mostafaberg** [comment]
Ok let's take this in a new issue and we can see what can be done

**Comment by jhanzo** [comment]
Thanks a lot

**Comment by pomozoff** [comment]
> Does it work when you add this to your cartfile ?
> 
> github "dexman/Minizip"

Nope, it still wants minizip module:

> /Users/user/Documents/Develop/test.swift:7:8: Missing required module 'minizip'

**Comment by icaksama** [comment]
Try this when build with carthage :
`carthage update --use-submodules`

**Comment by marmelroy** [comment]
Thanks @icaksama. 

I updated the Swift 2.3 README file to add the 
```
--use-submodules
```

**Comment by BaherHosni** [comment]
Well I had to.. Sorry.. 
I am getting the "Missing required module 'minizip'" too! So, I tried using the "carthage update --use-submodules" but now I am getting a new problem:

> _Bahers-Mac:Kansas baherhosni$ carthage update --use-submodules
> *** Cloning Zip
> *** Checking out Zip at "0.6.0"
> A shell task (/usr/bin/env git submodule --quiet init -- Carthage/Checkouts/Zip) failed with exit code 128:
> fatal: Not a git repository (or any of the parent directories): .git_

Another issue (https://github.com/Carthage/Carthage/issues/407) advised to clean Carthage's repository cache, but that didn't help. I am still stuck with the "Missing required module 'minizip'"

I hope you can help me with this!

**Comment by mostafaberg** [comment]
What's the contents of `Carthage/Checkouts/Zip`, just an empty dir ?

**Comment by mostafaberg** [comment]
I know you tried to clear the cache, but try the following steps:
```
rm -rf Carthage/Checkouts
rm -rf ~/.carthage/dependencies
rm -rf ~/Library/Caches/org.carthage.CarthageKit
carthage update --use-submodules
```

The error you're getting is basically saying that git tried to init the submodules `git submodule --quite init`, but found no repository in `Carthage/Checkouts/Zip`

**Comment by mostafaberg** [comment]
That is strange yes, maybe it's related to a Carthage bug ? are you on the latest version of Carthage?

**Comment by BaherHosni** [comment]
Yes.. Its a fresh install today.. :/

**Comment by mostafaberg** [comment]
Can we see your Cartfile ?

**Comment by BaherHosni** [comment]
Ok.. Seems I got around the error! But still didn't test the actual Zipping!  Here is what I had to do:

1. Disregarded the --use-submodules option
2. Went with your advise motafabreg about adding minizip in the Cartfile
3. Finally removed an extra reference in the "Framework Search Paths" under "Release" to "Carthage/Build/Mac" which was somehow causing xcode to produce errors too

**Comment by 1337mus** [comment]
Having the same issue on Xcode 9.2 using Carthage. Tried updating the Cartfile as mostafaberg  mentioned as well as using `carthage update --use-submodules` no dice :/ Any help appreciated

**Comment by udelunar** [comment]
I have the same issue with Xcode 10.1  :( 
In my home computer all work , but in other computer no.

Any help?

**Comment by RameshAran** [comment]
We are also facing the same problem. It works in some computer and not in some other computer....
Any suggestions.

Error while importing Zip getting error - "Missing required module 'minizip'"
