### ISSUE TITLE
Swift2.3 Cocoapods - minizip is missing 

### ISSUE THREAD

**Issue by jhanzo** [marmelroy/Zip#59]
Migration from swift 2.2 to 2.3 with XCode 8 triggers an error on build : 

> no such module 'minizip'

I tried to point on specific branch without success : 

`pod 'Zip', '~> 0.4'`
or 
`pod 'Zip', :git => 'https://github.com/marmelroy/Zip.git', :branch => 'swift2.3'`

**Comment by mostafaberg** [comment]
What other pods are you using ?

**Comment by jhanzo** [comment]
For security reason may I send you my podfile by mail ?

**Comment by mostafaberg** [comment]
Sure no worries just get in touch at `berg1[at]icloud[dot]com`

**Comment by mostafaberg** [comment]
Ok got your email, reviewed and updated everything to work with `Swift 3`, try to run your code migrator and see how things work, it's much easier to migrate to `Swift 3` than to migrate to `Swift 2.3` and not so long afterwards be forced to migrate to `Swift 3` when apple deprecates it completely

**Comment by jhanzo** [comment]
Thanks for your support and your quick answer 😄  In addition, I think issue of branch 2.3 provides from reference in this branch. Indeed when I clone your repository and git branch to swift2.3, minizip folder is empty whereas in branch swift3 it's not. Maybe copying pasting it as a source and not as a reference should be solved the issue on this branch.

**Comment by mostafaberg** [comment]
it is indeed, you can always add MiniZip to your project manually without cocoapods, or you can just check if it's actually a submodule, just check when you install the `swift2.3` branch if the submodules are initialized and downloaded

**Comment by lucatorella** [comment]
I'm also having the same issue, and I can't update to Swift 3 yet, because Alamofire dropped support for iOS 8 in their Swift 3 version. And I can drop iOS 8 only when it's below of 5% of our users. 

Can we have a version 0.4.4 that works with swift 2.3?

Temporarily I'll use the swift-2.3 branch and manually add the missing mini zip lib.

**Comment by jhanzo** [comment]
+1 
waiting for merged PR :  https://github.com/marmelroy/Zip/pull/61

**Comment by marmelroy** [comment]
Merged. That said, the Swift 2.3 branch will be deprecated soon and we recommend moving to the Swift 3 version.
