### ISSUE TITLE
Help in Unzip file downloaded from server 

### ISSUE THREAD

**Issue by trandinhlinh94** [marmelroy/Zip#64]
Hi i am trying to unzip a file download from server. But i couldn't do it somehow. Could anyone help me to figure out a solution for this. Here is my code: 

func webLoadContent() {
        // Download zip file from server
        
        let documentsDirectoryUrl =  FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first as! NSURL
        
        let sourceUrl = NSURL(string:"https://www.dropbox.com/s/o3uqrtxancfq1f2/test.zip?dl=0")
        
        //Get the file name and create a destination URL
        let file = sourceUrl?.lastPathComponent!
        let destinationURL = documentsDirectoryUrl.appendingPathComponent(file!)
        //Hold this file as an NSData and write it to the new location
        if let fileData = NSData(contentsOf: sourceUrl as! URL) {
            fileData.write(to: destinationURL!, atomically: false)   // true
            print("file path: \(destinationURL!.path) ")
            print("file name: \(destinationURL!.lastPathComponent)")
        }
        
        // Unzip file
        let url1 = NSURL(string: destinationURL!.path)
        do {
            let unzipURL =   try Zip.unzipFile(url1 as! URL, destination: documentsDirectoryUrl as URL, overwrite: true, password: nil, progress: { (progress) -> () in
                print(progress)
            }) // Unzip
        }catch {
            print("failed to unzip file")
        }
}

**Comment by marmelroy** [comment]
Hi @trandinhlinh94 - the URL is wrong. It is pointing at an html file and not a zip file.

**Comment by trandinhlinh94** [comment]
Hi @marmelroy, how could i point it to the zip file? Could you show me? thanks!

**Comment by marmelroy** [comment]
Try hosting it outside of Dropbox (on a real server) and have a direct path to the file
