### ISSUE TITLE
This does not work with macOS app files

### ISSUE THREAD

**Issue by chess92** [marmelroy/Zip#65]
I have archived an app I made from XCode. I zip it with the standard macOS compress from the right click menu.

But Zip does not upzip it properly. When I try to double click the app file, it says the file is corrupted.

**Comment by marmelroy** [comment]
Thanks @chess92 - can you please share the standard macOS zip here so I can debug?

**Comment by chess92** [comment]
[SampleApp.app.zip](https://github.com/marmelroy/Zip/files/646463/SampleApp.app.zip) is an example. If you double click on it, it extracts a mac application. The application runs fine (it is just an empty window that says Sample app at the top)

But it won't unzip properly from the Zip framework.

**Comment by marmelroy** [comment]
Thanks a lot, I will investigate tonight

**Comment by marmelroy** [comment]
Hi @chess92, sorry for the delay. So I checked and the main issue here is the file name. It's quite a long story but mac apps are actually directories and Zip is using the file name as the name for the containing destination directory. What gets created looks like an app but is actually a directory containing the app.

Confusing, I know. 

The solution is to change the file name 😄.

**Comment by chess92** [comment]
So I have to name my app package different just to use your framework?

**Comment by marmelroy** [comment]
If you can't change the file name (of the zip file, not the app), you can also use the unzipFile method and specify a custom destination. quickUnzipFile is just a convenience method.
