### ISSUE TITLE
how can i add the framework to the project without using cocoa pod

### ISSUE THREAD

**Issue by brttcgcg** [marmelroy/Zip#67]
Is there a way to add this framework to the xcode project without using cocoapod

**Comment by DevAndArtist** [comment]
@brttcgcg Please do not open an issue when you're not even reading the README on this repository. 😒

If you don't know how Cocoapods works, you can start learning it [here](https://www.youtube.com/watch?v=iEAjvNRdZa0&spfreload=10).

**Comment by mostafaberg** [comment]
Cleaning up lingering open issues, please reopen a new one if you didn't manage to install the library without CocoaPods yet
