### ISSUE TITLE
can i unzip two files in the same time?

### ISSUE THREAD

**Issue by d1248966459** [marmelroy/Zip#68]
i mean, can i have two or many unzip tasks work in the same time?

**Comment by mostafaberg** [comment]
Theoretically there shouldn't be any issue with that, best way is to just try and see if it works or not, simply run multiple unzip commands on a couple different threads and see how it goes, i guess it'll work out. closing as this is not really an issue 👍

**Comment by d1248966459** [comment]
so one thread one unzip task?

**Comment by mostafaberg** [comment]
I would say so, or try GCD, multiple async operations, etc..

**Comment by d1248966459** [comment]
Thank you very much， let me have a try
