### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by bmaupin** [marmelroy/Zip#82]
I'm unable to install Zip with Swift Package Manager:

    $ swift package update
    Fetching https://github.com/marmelroy/Zip.git
    error: https://github.com/marmelroy/Zip.git has no manifest for version 0.7.0

Contents of my Package.swift:

    import PackageDescription

    let package = Package(
        name: "Test",
        dependencies: [
            .Package(url: "https://github.com/marmelroy/Zip.git",
                     majorVersion: 0),
        ]
    )

**Comment by mostafaberg** [comment]
There is no SPM support for Zip at the moment as it's dependencies aren't written in swift.
SPM only works with Swift code and doesn't support any mixing, so until everything is ported to Swift, it's not going to be possible

**Comment by numen31337** [comment]
Here is the example of the similar lib which relying on minizip aswell https://github.com/PerfectlySoft/Perfect-Zip
I believe that Swift Package Manager support will be very useful for a lot of people.

**Comment by mostafaberg** [comment]
I'm sorry I didn't explain the issue clearly, the library has minizip bundled with the same source, not as a dependency, which SPM doesn't support, as you see in [this issue](https://github.com/marmelroy/Zip/issues/52) for example.

I think it's easy to get this fixed for SPM, but that also means the C code has to be removed, which is going to break the Cocoapods and Carthage builds, alternatives needs to be found.

I don't have so much time to look into this at the moment so can't promise things will change very quickly, but if you have some time to spare I would recommend giving it a shot :)

I think the last version that had that file was [0.5.0](https://github.com/marmelroy/Zip/releases/tag/0.5.0) try that in your Package.swift file to see a better overview of what happens.
