### ISSUE TITLE
Cocoapod doc doesn't work

### ISSUE THREAD

**Issue by tethridge** [marmelroy/Zip#85]
Will there be a 0.7.0 release soon?  I need the Swift 3.0 version and I would prefer to use the cocoapod.  The current doc recommends using "pod 'Zip', '\~> 0.7'", which doesn't work.  The doc should remove the '\~> 0.7' or 0.7 needs to be rolled out.  0.6 release installs fine, but I need the Swift 3.0 updates.

Here is the error I'm seeing when I try to specify 0.7:
```
$ pod install
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Zip (~> 0.7)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Zip (~> 0.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by mostafaberg** [comment]
As it says in the error message, your repo is out of date, run `pod repo update` to update your installation (sometimes the process is slow)version 0.7 will be available afterwards as it's already released. good luck!

**Comment by tethridge** [comment]
Thanks for the quick reply.  That worked.  I was confused as to why the releases page lists the 0.7 build, but it isn't marked as the latest release.
