### ISSUE TITLE
Xcode9's new build system produces : No such module 'minizip'

### ISSUE THREAD

**Issue by rlimberger** [marmelroy/Zip#93]
When using Zip with Xcode9's new build system, we are getting the "No such module 'minizip'" error. This is not an issue when using Xcode9 with the old build system or Xcode 8.3.3. 

We just wanted to flag this as an issue. 

Thanks.

**Comment by DanielAsher** [comment]
We have worked around this by including the Zip project in our workspace. This seems to solve the issue, but is not ideal.

**Comment by AvdLee** [comment]
This should be fixed with #119.
